# Generated by Django 5.0.6 on 2024-06-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('img', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, max_length=20)),
            ],
        ),
    ]
