# Generated by Django 5.0.6 on 2024-06-14 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menucategory_menuitem_delete_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='catgory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='menu.menucategory'),
        ),
    ]
